Repository macroenergy/Dolphyn.jl, pull requests merged in 2022-11, with the labels that each got.

#98 Added backup line-by-line file comparison
  Example_Systems/2030_CombEC_DETrans/Check_results.jl
  Example_Systems/SmallNewEngland/OneZone/Check_results.jl
  Example_Systems/SmallNewEngland/ThreeZones/Check_results.jl
  src/compare_results.jl
Labels: bug, DOLPHYN UX

#102 pin gurobi as 0.11.3
  julenv.jl
Labels: DOLPHYN structure

#105 Change chemicals rendering style and fix typos
  docs/make.jl
  docs/src/genx_data_documentation.md
  docs/src/global_data_documentation.md
  docs/src/hsc_data_documentation.md
  docs/src/hsc_notation.md
  docs/src/index.md
  docs/src/model_introduction.md
  docs/src/solvers.md
  src/configure_solver/configure_cplex.jl
  src/configure_solver/configure_gurobi.jl
  src/configure_solver/configure_solver.jl
Labels: documentation

#99 add truck costs and transmission flow
  Example_Systems/SmallNewEngland/ThreeZones/HSC_zone_truck_distances_miles.csv
  src/DOLPHYN.jl
  src/HSC/write_outputs/write_HSC_outputs.jl
  src/HSC/write_outputs/write_h2_costs.jl
  src/HSC/write_outputs/write_h2_transmission_flow.jl
Labels: Sector models, Technology representation

#106 Allow Julia 1.8 with DOLPHYN
  src/GenX/write_outputs/capacity_reserve_margin/write_capacity_value.jl
  src/GenX/write_outputs/transmission/write_transmission_flows.jl
  src/GenX/write_outputs/transmission/write_transmission_losses.jl
  src/GenX/write_outputs/ucommit/write_shutdown.jl
  src/GenX/write_outputs/write_charge.jl
  src/GenX/write_outputs/write_curtailment.jl
  src/GenX/write_outputs/write_emissions.jl
  src/GenX/write_outputs/write_net_revenue.jl
  src/GenX/write_outputs/write_nse.jl
  src/GenX/write_outputs/write_power.jl
  src/GenX/write_outputs/write_subsidy_revenue.jl
  src/HSC/write_outputs/write_h2_charge.jl
  src/HSC/write_outputs/write_h2_emissions.jl
  src/HSC/write_outputs/write_h2_nse.jl
Labels: bug

#108 Fix bug in the 2030_CombEC_DETrans example
  Example_Systems/2030_CombEC_DETrans/Run.jl
  Example_Systems/2030_CombEC_DETrans/Settings/global_model_settings.yml
Labels: bug

#107 Fix bug in how compare_results.jl prints missing files
  src/compare_results.jl
Labels: bug, enhancement, DOLPHYN UX
